---
title: RB9 blog
tagline: Arr bee nine? Arr-benign?
description: |
  Arr bee nine? Arr-benign?<br />
  ¯\_(ツ)_/¯
url: https://rb9.nl
author:
  name: Khaled Nassar
  url: https://twitter.com/khalednassar
paginate: 5
paginate_path: /blog/page:num/
blog_home_path: '/blog/'
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
sidebar_home_link: false
sidebar_main_link: '/'
blog_assets_location: '/blog/assets'
layout-reverse: false
remote_theme: khalednassar/hydeout
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/
feed:
  path: /blog/feed.xml
site_repo_url: 'https://github.com/khalednassar/khalednassar.github.io/'
